// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWSU9lpFeLcSy0wsSQ9dg4kKX6nbXhzs',
    appId: '1:1000926527239:web:0dfe9a3f262d9764c30fa2',
    messagingSenderId: '1000926527239',
    projectId: 'mynotes69',
    authDomain: 'mynotes69.firebaseapp.com',
    storageBucket: 'mynotes69.appspot.com',
    measurementId: 'G-8NFY04DH10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRn0LQNP-nsDN5f_gSNcBAsHYfXDmuqDc',
    appId: '1:1000926527239:android:95739fcf3608528dc30fa2',
    messagingSenderId: '1000926527239',
    projectId: 'mynotes69',
    storageBucket: 'mynotes69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIRHW8Gn-I-lh4CKGVmil29GEh6Qb13E',
    appId: '1:1000926527239:ios:d33d740a9ed415c1c30fa2',
    messagingSenderId: '1000926527239',
    projectId: 'mynotes69',
    storageBucket: 'mynotes69.appspot.com',
    iosClientId: '1000926527239-5qsplc0s2908m102evtorm9vt1vc28mu.apps.googleusercontent.com',
    iosBundleId: 'in.berrydays.strawberrydaydreams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIRHW8Gn-I-lh4CKGVmil29GEh6Qb13E',
    appId: '1:1000926527239:ios:d33d740a9ed415c1c30fa2',
    messagingSenderId: '1000926527239',
    projectId: 'mynotes69',
    storageBucket: 'mynotes69.appspot.com',
    iosClientId: '1000926527239-5qsplc0s2908m102evtorm9vt1vc28mu.apps.googleusercontent.com',
    iosBundleId: 'in.berrydays.strawberrydaydreams',
  );
}
