// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCitTFmoWJrfFFnBLtPYri46nYPUcSBGr4',
    appId: '1:990350557183:web:a677613c68c6302b5771ca',
    messagingSenderId: '990350557183',
    projectId: 'pocketpg-e8d80',
    authDomain: 'pocketpg-e8d80.firebaseapp.com',
    storageBucket: 'pocketpg-e8d80.appspot.com',
    measurementId: 'G-DE1EMEFWM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGcmGq8DQdaOX-R9du5sPHdHfZMIBHmk',
    appId: '1:990350557183:android:d6341079402dce385771ca',
    messagingSenderId: '990350557183',
    projectId: 'pocketpg-e8d80',
    storageBucket: 'pocketpg-e8d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWfgvs_MNoQV87y30ykUuE3W5JMlAiOG8',
    appId: '1:990350557183:ios:772b810373c8e9a05771ca',
    messagingSenderId: '990350557183',
    projectId: 'pocketpg-e8d80',
    storageBucket: 'pocketpg-e8d80.appspot.com',
    iosClientId: '990350557183-rhgho4sbqq6mf72oojff37i6ne29qvfk.apps.googleusercontent.com',
    iosBundleId: 'in.berrydays.strawberrydaydreams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWfgvs_MNoQV87y30ykUuE3W5JMlAiOG8',
    appId: '1:990350557183:ios:772b810373c8e9a05771ca',
    messagingSenderId: '990350557183',
    projectId: 'pocketpg-e8d80',
    storageBucket: 'pocketpg-e8d80.appspot.com',
    iosClientId: '990350557183-rhgho4sbqq6mf72oojff37i6ne29qvfk.apps.googleusercontent.com',
    iosBundleId: 'in.berrydays.strawberrydaydreams',
  );
}
